name: search_github
description: Search GitHub repositories App
publish_to: 'none' 
version: 1.0.0+1


environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  # for l10n
  flutter_localizations:
    sdk: flutter
  
  # riverpod
  flutter_riverpod: ^2.1.1

  # routemaster for routing
  routemaster: ^1.0.1

  # auto size text
  auto_size_text: ^3.0.0

  # responsive design
  flutter_screenutil: ^5.6.0

  # JSON
  json_serializable: ^6.5.4
  
  # Multisize Simulator
  device_preview: ^1.1.0
  
  # http
  http: ^0.13.5

  # for resposible design
  responsive_framework: ^0.2.0
  sizer: ^2.0.15

  # for multilingual support
  l10n_flutter: ^1.0.6
  

  # for l10n
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # freezed
  freezed: ^2.2.1
  freezed_annotation:

  # build runner for freezed & l10n
  build_runner: ^2.3.2


flutter:
  uses-material-design: true
  generate: true # for l10n

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
