name: search_github
description: Search GitHub repositories App
publish_to: 'none' 
version: 1.0.0+1


environment:
  sdk: '>=2.17.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  # for l10n
  flutter_localizations:
    sdk: flutter
  
  # riverpod
  flutter_riverpod: ^1.0.3

  # routemaster for routing
  routemaster: ^1.0.1

  # auto size text
  auto_size_text: ^3.0.0

  # responsive design
  flutter_screenutil: ^5.6.0

  # JSON
  json_serializable: ^6.3.1
  
  # Multisize Simulator
  device_preview: ^1.1.0
  
  # http
  http: ^0.13.5

  # for multilingual support
  l10n_flutter: ^1.0.6
  
  # for l10n
  intl: ^0.17.0
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # freezed
  freezed: ^2.2.1
  freezed_annotation:

  # build runner for freezed & l10n
  build_runner: ^2.3.2

  # network image test
  network_image_mock: ^2.1.1

  # mock web server for Unit test
  mock_web_server: ^5.0.0-nullsafety.1
  mockito: ^5.3.2

  # DI for mock test
  get_it: ^7.2.0
  
  # Integration test
  integration_test:
    sdk: flutter


flutter:
  assets:
    - assets/images/
  uses-material-design: true
  generate: true # for l10n
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
