import 'dart:convert';
import 'package:flutter_test/flutter_test.dart';
import 'package:search_github/data_model/items.dart';
import 'package:search_github/data_model/search_repository_model.dart';

void main() {
  String githubApiSearchRepositoryReturnDataExample = '''
{
    "total_count": 5050,
    "incomplete_results": false,
    "items": [
        {
            "id": 77338532,
            "node_id": "MDEwOlJlcG9zaXRvcnk3NzMzODUzMg==",
            "name": "cross",
            "full_name": "cross-rs/cross",
            "private": false,
            "owner": {
                "login": "cross-rs",
                "id": 93954236,
                "node_id": "O_kgDOBZmgvA",
                "avatar_url": "https://avatars.githubusercontent.com/u/93954236?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/cross-rs",
                "html_url": "https://github.com/cross-rs",
                "followers_url": "https://api.github.com/users/cross-rs/followers",
                "following_url": "https://api.github.com/users/cross-rs/following{/other_user}",
                "gists_url": "https://api.github.com/users/cross-rs/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/cross-rs/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/cross-rs/subscriptions",
                "organizations_url": "https://api.github.com/users/cross-rs/orgs",
                "repos_url": "https://api.github.com/users/cross-rs/repos",
                "events_url": "https://api.github.com/users/cross-rs/events{/privacy}",
                "received_events_url": "https://api.github.com/users/cross-rs/received_events",
                "type": "Organization",
                "site_admin": false
            },
            "html_url": "https://github.com/cross-rs/cross",
            "description": "“Zero setup” cross compilation and “cross testing” of Rust crates",
            "fork": false,
            "url": "https://api.github.com/repos/cross-rs/cross",
            "forks_url": "https://api.github.com/repos/cross-rs/cross/forks",
            "keys_url": "https://api.github.com/repos/cross-rs/cross/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/cross-rs/cross/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/cross-rs/cross/teams",
            "hooks_url": "https://api.github.com/repos/cross-rs/cross/hooks",
            "issue_events_url": "https://api.github.com/repos/cross-rs/cross/issues/events{/number}",
            "events_url": "https://api.github.com/repos/cross-rs/cross/events",
            "assignees_url": "https://api.github.com/repos/cross-rs/cross/assignees{/user}",
            "branches_url": "https://api.github.com/repos/cross-rs/cross/branches{/branch}",
            "tags_url": "https://api.github.com/repos/cross-rs/cross/tags",
            "blobs_url": "https://api.github.com/repos/cross-rs/cross/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/cross-rs/cross/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/cross-rs/cross/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/cross-rs/cross/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/cross-rs/cross/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/cross-rs/cross/languages",
            "stargazers_url": "https://api.github.com/repos/cross-rs/cross/stargazers",
            "contributors_url": "https://api.github.com/repos/cross-rs/cross/contributors",
            "subscribers_url": "https://api.github.com/repos/cross-rs/cross/subscribers",
            "subscription_url": "https://api.github.com/repos/cross-rs/cross/subscription",
            "commits_url": "https://api.github.com/repos/cross-rs/cross/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/cross-rs/cross/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/cross-rs/cross/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/cross-rs/cross/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/cross-rs/cross/contents/{+path}",
            "compare_url": "https://api.github.com/repos/cross-rs/cross/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/cross-rs/cross/merges",
            "archive_url": "https://api.github.com/repos/cross-rs/cross/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/cross-rs/cross/downloads",
            "issues_url": "https://api.github.com/repos/cross-rs/cross/issues{/number}",
            "pulls_url": "https://api.github.com/repos/cross-rs/cross/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/cross-rs/cross/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/cross-rs/cross/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/cross-rs/cross/labels{/name}",
            "releases_url": "https://api.github.com/repos/cross-rs/cross/releases{/id}",
            "deployments_url": "https://api.github.com/repos/cross-rs/cross/deployments",
            "created_at": "2016-12-25T18:48:10Z",
            "updated_at": "2022-12-03T15:05:09Z",
            "pushed_at": "2022-12-04T06:34:32Z",
            "git_url": "git://github.com/cross-rs/cross.git",
            "ssh_url": "git@github.com:cross-rs/cross.git",
            "clone_url": "https://github.com/cross-rs/cross.git",
            "svn_url": "https://github.com/cross-rs/cross",
            "homepage": "",
            "size": 2754,
            "stargazers_count": 3885,
            "watchers_count": 3885,
            "language": "Rust",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "has_discussions": true,
            "forks_count": 256,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 62,
            "license": {
                "key": "apache-2.0",
                "name": "Apache License 2.0",
                "spdx_id": "Apache-2.0",
                "url": "https://api.github.com/licenses/apache-2.0",
                "node_id": "MDc6TGljZW5zZTI="
            },
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [
                "aarch64",
                "arm",
                "bsd",
                "cargo",
                "cross-compilation",
                "cross-testing",
                "linux",
                "mips",
                "powerpc",
                "rust",
                "s390x",
                "sparc",
                "windows",
                "x86"
            ],
            "visibility": "public",
            "forks": 256,
            "open_issues": 62,
            "watchers": 3885,
            "default_branch": "main",
            "score": 1.0
        },
        {
            "id": 29821195,
            "node_id": "MDEwOlJlcG9zaXRvcnkyOTgyMTE5NQ==",
            "name": "rust-bio",
            "full_name": "rust-bio/rust-bio",
            "private": false,
            "owner": {
                "login": "rust-bio",
                "id": 13785584,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzNzg1NTg0",
                "avatar_url": "https://avatars.githubusercontent.com/u/13785584?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/rust-bio",
                "html_url": "https://github.com/rust-bio",
                "followers_url": "https://api.github.com/users/rust-bio/followers",
                "following_url": "https://api.github.com/users/rust-bio/following{/other_user}",
                "gists_url": "https://api.github.com/users/rust-bio/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/rust-bio/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/rust-bio/subscriptions",
                "organizations_url": "https://api.github.com/users/rust-bio/orgs",
                "repos_url": "https://api.github.com/users/rust-bio/repos",
                "events_url": "https://api.github.com/users/rust-bio/events{/privacy}",
                "received_events_url": "https://api.github.com/users/rust-bio/received_events",
                "type": "Organization",
                "site_admin": false
            },
            "html_url": "https://github.com/rust-bio/rust-bio",
            "description": "This library provides implementations of many algorithms and data structures that are useful for bioinformatics. All provided implementations are rigorously tested via continuous integration.",
            "fork": false,
            "url": "https://api.github.com/repos/rust-bio/rust-bio",
            "forks_url": "https://api.github.com/repos/rust-bio/rust-bio/forks",
            "keys_url": "https://api.github.com/repos/rust-bio/rust-bio/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/rust-bio/rust-bio/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/rust-bio/rust-bio/teams",
            "hooks_url": "https://api.github.com/repos/rust-bio/rust-bio/hooks",
            "issue_events_url": "https://api.github.com/repos/rust-bio/rust-bio/issues/events{/number}",
            "events_url": "https://api.github.com/repos/rust-bio/rust-bio/events",
            "assignees_url": "https://api.github.com/repos/rust-bio/rust-bio/assignees{/user}",
            "branches_url": "https://api.github.com/repos/rust-bio/rust-bio/branches{/branch}",
            "tags_url": "https://api.github.com/repos/rust-bio/rust-bio/tags",
            "blobs_url": "https://api.github.com/repos/rust-bio/rust-bio/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/rust-bio/rust-bio/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/rust-bio/rust-bio/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/rust-bio/rust-bio/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/rust-bio/rust-bio/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/rust-bio/rust-bio/languages",
            "stargazers_url": "https://api.github.com/repos/rust-bio/rust-bio/stargazers",
            "contributors_url": "https://api.github.com/repos/rust-bio/rust-bio/contributors",
            "subscribers_url": "https://api.github.com/repos/rust-bio/rust-bio/subscribers",
            "subscription_url": "https://api.github.com/repos/rust-bio/rust-bio/subscription",
            "commits_url": "https://api.github.com/repos/rust-bio/rust-bio/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/rust-bio/rust-bio/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/rust-bio/rust-bio/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/rust-bio/rust-bio/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/rust-bio/rust-bio/contents/{+path}",
            "compare_url": "https://api.github.com/repos/rust-bio/rust-bio/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/rust-bio/rust-bio/merges",
            "archive_url": "https://api.github.com/repos/rust-bio/rust-bio/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/rust-bio/rust-bio/downloads",
            "issues_url": "https://api.github.com/repos/rust-bio/rust-bio/issues{/number}",
            "pulls_url": "https://api.github.com/repos/rust-bio/rust-bio/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/rust-bio/rust-bio/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/rust-bio/rust-bio/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/rust-bio/rust-bio/labels{/name}",
            "releases_url": "https://api.github.com/repos/rust-bio/rust-bio/releases{/id}",
            "deployments_url": "https://api.github.com/repos/rust-bio/rust-bio/deployments",
            "created_at": "2015-01-25T16:40:31Z",
            "updated_at": "2022-12-03T11:54:11Z",
            "pushed_at": "2022-12-03T12:39:51Z",
            "git_url": "git://github.com/rust-bio/rust-bio.git",
            "ssh_url": "git@github.com:rust-bio/rust-bio.git",
            "clone_url": "https://github.com/rust-bio/rust-bio.git",
            "svn_url": "https://github.com/rust-bio/rust-bio",
            "homepage": "https://rust-bio.github.io",
            "size": 2620,
            "stargazers_count": 1192,
            "watchers_count": 1192,
            "language": "Rust",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "has_discussions": false,
            "forks_count": 167,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 91,
            "license": {
                "key": "mit",
                "name": "MIT License",
                "spdx_id": "MIT",
                "url": "https://api.github.com/licenses/mit",
                "node_id": "MDc6TGljZW5zZTEz"
            },
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [],
            "visibility": "public",
            "forks": 167,
            "open_issues": 91,
            "watchers": 1192,
            "default_branch": "master",
            "score": 1.0
        },
        {
            "id": 94702898,
            "node_id": "MDEwOlJlcG9zaXRvcnk5NDcwMjg5OA==",
            "name": "proptest",
            "full_name": "proptest-rs/proptest",
            "private": false,
            "owner": {
                "login": "proptest-rs",
                "id": 116231032,
                "node_id": "O_kgDOBu2LeA",
                "avatar_url": "https://avatars.githubusercontent.com/u/116231032?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/proptest-rs",
                "html_url": "https://github.com/proptest-rs",
                "followers_url": "https://api.github.com/users/proptest-rs/followers",
                "following_url": "https://api.github.com/users/proptest-rs/following{/other_user}",
                "gists_url": "https://api.github.com/users/proptest-rs/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/proptest-rs/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/proptest-rs/subscriptions",
                "organizations_url": "https://api.github.com/users/proptest-rs/orgs",
                "repos_url": "https://api.github.com/users/proptest-rs/repos",
                "events_url": "https://api.github.com/users/proptest-rs/events{/privacy}",
                "received_events_url": "https://api.github.com/users/proptest-rs/received_events",
                "type": "Organization",
                "site_admin": false
            },
            "html_url": "https://github.com/proptest-rs/proptest",
            "description": "Hypothesis-like property testing for Rust",
            "fork": false,
            "url": "https://api.github.com/repos/proptest-rs/proptest",
            "forks_url": "https://api.github.com/repos/proptest-rs/proptest/forks",
            "keys_url": "https://api.github.com/repos/proptest-rs/proptest/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/proptest-rs/proptest/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/proptest-rs/proptest/teams",
            "hooks_url": "https://api.github.com/repos/proptest-rs/proptest/hooks",
            "issue_events_url": "https://api.github.com/repos/proptest-rs/proptest/issues/events{/number}",
            "events_url": "https://api.github.com/repos/proptest-rs/proptest/events",
            "assignees_url": "https://api.github.com/repos/proptest-rs/proptest/assignees{/user}",
            "branches_url": "https://api.github.com/repos/proptest-rs/proptest/branches{/branch}",
            "tags_url": "https://api.github.com/repos/proptest-rs/proptest/tags",
            "blobs_url": "https://api.github.com/repos/proptest-rs/proptest/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/proptest-rs/proptest/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/proptest-rs/proptest/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/proptest-rs/proptest/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/proptest-rs/proptest/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/proptest-rs/proptest/languages",
            "stargazers_url": "https://api.github.com/repos/proptest-rs/proptest/stargazers",
            "contributors_url": "https://api.github.com/repos/proptest-rs/proptest/contributors",
            "subscribers_url": "https://api.github.com/repos/proptest-rs/proptest/subscribers",
            "subscription_url": "https://api.github.com/repos/proptest-rs/proptest/subscription",
            "commits_url": "https://api.github.com/repos/proptest-rs/proptest/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/proptest-rs/proptest/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/proptest-rs/proptest/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/proptest-rs/proptest/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/proptest-rs/proptest/contents/{+path}",
            "compare_url": "https://api.github.com/repos/proptest-rs/proptest/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/proptest-rs/proptest/merges",
            "archive_url": "https://api.github.com/repos/proptest-rs/proptest/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/proptest-rs/proptest/downloads",
            "issues_url": "https://api.github.com/repos/proptest-rs/proptest/issues{/number}",
            "pulls_url": "https://api.github.com/repos/proptest-rs/proptest/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/proptest-rs/proptest/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/proptest-rs/proptest/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/proptest-rs/proptest/labels{/name}",
            "releases_url": "https://api.github.com/repos/proptest-rs/proptest/releases{/id}",
            "deployments_url": "https://api.github.com/repos/proptest-rs/proptest/deployments",
            "created_at": "2017-06-18T17:38:03Z",
            "updated_at": "2022-11-30T15:30:22Z",
            "pushed_at": "2022-11-30T17:17:21Z",
            "git_url": "git://github.com/proptest-rs/proptest.git",
            "ssh_url": "git@github.com:proptest-rs/proptest.git",
            "clone_url": "https://github.com/proptest-rs/proptest.git",
            "svn_url": "https://github.com/proptest-rs/proptest",
            "homepage": null,
            "size": 1508,
            "stargazers_count": 1129,
            "watchers_count": 1129,
            "language": "Rust",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "has_discussions": false,
            "forks_count": 116,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 103,
            "license": {
                "key": "apache-2.0",
                "name": "Apache License 2.0",
                "spdx_id": "Apache-2.0",
                "url": "https://api.github.com/licenses/apache-2.0",
                "node_id": "MDc6TGljZW5zZTI="
            },
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [],
            "visibility": "public",
            "forks": 116,
            "open_issues": 103,
            "watchers": 1129,
            "default_branch": "master",
            "score": 1.0
        },
        {
            "id": 54234138,
            "node_id": "MDEwOlJlcG9zaXRvcnk1NDIzNDEzOA==",
            "name": "rust-crdt",
            "full_name": "rust-crdt/rust-crdt",
            "private": false,
            "owner": {
                "login": "rust-crdt",
                "id": 43778892,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjQzNzc4ODky",
                "avatar_url": "https://avatars.githubusercontent.com/u/43778892?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/rust-crdt",
                "html_url": "https://github.com/rust-crdt",
                "followers_url": "https://api.github.com/users/rust-crdt/followers",
                "following_url": "https://api.github.com/users/rust-crdt/following{/other_user}",
                "gists_url": "https://api.github.com/users/rust-crdt/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/rust-crdt/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/rust-crdt/subscriptions",
                "organizations_url": "https://api.github.com/users/rust-crdt/orgs",
                "repos_url": "https://api.github.com/users/rust-crdt/repos",
                "events_url": "https://api.github.com/users/rust-crdt/events{/privacy}",
                "received_events_url": "https://api.github.com/users/rust-crdt/received_events",
                "type": "Organization",
                "site_admin": false
            },
            "html_url": "https://github.com/rust-crdt/rust-crdt",
            "description": "a collection of well-tested, serializable CRDTs for Rust",
            "fork": false,
            "url": "https://api.github.com/repos/rust-crdt/rust-crdt",
            "forks_url": "https://api.github.com/repos/rust-crdt/rust-crdt/forks",
            "keys_url": "https://api.github.com/repos/rust-crdt/rust-crdt/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/rust-crdt/rust-crdt/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/rust-crdt/rust-crdt/teams",
            "hooks_url": "https://api.github.com/repos/rust-crdt/rust-crdt/hooks",
            "issue_events_url": "https://api.github.com/repos/rust-crdt/rust-crdt/issues/events{/number}",
            "events_url": "https://api.github.com/repos/rust-crdt/rust-crdt/events",
            "assignees_url": "https://api.github.com/repos/rust-crdt/rust-crdt/assignees{/user}",
            "branches_url": "https://api.github.com/repos/rust-crdt/rust-crdt/branches{/branch}",
            "tags_url": "https://api.github.com/repos/rust-crdt/rust-crdt/tags",
            "blobs_url": "https://api.github.com/repos/rust-crdt/rust-crdt/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/rust-crdt/rust-crdt/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/rust-crdt/rust-crdt/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/rust-crdt/rust-crdt/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/rust-crdt/rust-crdt/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/rust-crdt/rust-crdt/languages",
            "stargazers_url": "https://api.github.com/repos/rust-crdt/rust-crdt/stargazers",
            "contributors_url": "https://api.github.com/repos/rust-crdt/rust-crdt/contributors",
            "subscribers_url": "https://api.github.com/repos/rust-crdt/rust-crdt/subscribers",
            "subscription_url": "https://api.github.com/repos/rust-crdt/rust-crdt/subscription",
            "commits_url": "https://api.github.com/repos/rust-crdt/rust-crdt/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/rust-crdt/rust-crdt/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/rust-crdt/rust-crdt/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/rust-crdt/rust-crdt/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/rust-crdt/rust-crdt/contents/{+path}",
            "compare_url": "https://api.github.com/repos/rust-crdt/rust-crdt/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/rust-crdt/rust-crdt/merges",
            "archive_url": "https://api.github.com/repos/rust-crdt/rust-crdt/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/rust-crdt/rust-crdt/downloads",
            "issues_url": "https://api.github.com/repos/rust-crdt/rust-crdt/issues{/number}",
            "pulls_url": "https://api.github.com/repos/rust-crdt/rust-crdt/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/rust-crdt/rust-crdt/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/rust-crdt/rust-crdt/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/rust-crdt/rust-crdt/labels{/name}",
            "releases_url": "https://api.github.com/repos/rust-crdt/rust-crdt/releases{/id}",
            "deployments_url": "https://api.github.com/repos/rust-crdt/rust-crdt/deployments",
            "created_at": "2016-03-18T22:03:02Z",
            "updated_at": "2022-11-30T18:23:09Z",
            "pushed_at": "2022-09-06T20:02:01Z",
            "git_url": "git://github.com/rust-crdt/rust-crdt.git",
            "ssh_url": "git@github.com:rust-crdt/rust-crdt.git",
            "clone_url": "https://github.com/rust-crdt/rust-crdt.git",
            "svn_url": "https://github.com/rust-crdt/rust-crdt",
            "homepage": "",
            "size": 685,
            "stargazers_count": 1021,
            "watchers_count": 1021,
            "language": "Rust",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "has_discussions": true,
            "forks_count": 46,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 17,
            "license": {
                "key": "apache-2.0",
                "name": "Apache License 2.0",
                "spdx_id": "Apache-2.0",
                "url": "https://api.github.com/licenses/apache-2.0",
                "node_id": "MDc6TGljZW5zZTI="
            },
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [
                "crdt",
                "distributed-systems",
                "rust",
                "serialization"
            ],
            "visibility": "public",
            "forks": 46,
            "open_issues": 17,
            "watchers": 1021,
            "default_branch": "master",
            "score": 1.0
        },
        {
            "id": 161875917,
            "node_id": "MDEwOlJlcG9zaXRvcnkxNjE4NzU5MTc=",
            "name": "loom",
            "full_name": "tokio-rs/loom",
            "private": false,
            "owner": {
                "login": "tokio-rs",
                "id": 20248544,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjIwMjQ4NTQ0",
                "avatar_url": "https://avatars.githubusercontent.com/u/20248544?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/tokio-rs",
                "html_url": "https://github.com/tokio-rs",
                "followers_url": "https://api.github.com/users/tokio-rs/followers",
                "following_url": "https://api.github.com/users/tokio-rs/following{/other_user}",
                "gists_url": "https://api.github.com/users/tokio-rs/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/tokio-rs/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/tokio-rs/subscriptions",
                "organizations_url": "https://api.github.com/users/tokio-rs/orgs",
                "repos_url": "https://api.github.com/users/tokio-rs/repos",
                "events_url": "https://api.github.com/users/tokio-rs/events{/privacy}",
                "received_events_url": "https://api.github.com/users/tokio-rs/received_events",
                "type": "Organization",
                "site_admin": false
            },
            "html_url": "https://github.com/tokio-rs/loom",
            "description": "Concurrency permutation testing tool for Rust.",
            "fork": false,
            "url": "https://api.github.com/repos/tokio-rs/loom",
            "forks_url": "https://api.github.com/repos/tokio-rs/loom/forks",
            "keys_url": "https://api.github.com/repos/tokio-rs/loom/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/tokio-rs/loom/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/tokio-rs/loom/teams",
            "hooks_url": "https://api.github.com/repos/tokio-rs/loom/hooks",
            "issue_events_url": "https://api.github.com/repos/tokio-rs/loom/issues/events{/number}",
            "events_url": "https://api.github.com/repos/tokio-rs/loom/events",
            "assignees_url": "https://api.github.com/repos/tokio-rs/loom/assignees{/user}",
            "branches_url": "https://api.github.com/repos/tokio-rs/loom/branches{/branch}",
            "tags_url": "https://api.github.com/repos/tokio-rs/loom/tags",
            "blobs_url": "https://api.github.com/repos/tokio-rs/loom/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/tokio-rs/loom/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/tokio-rs/loom/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/tokio-rs/loom/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/tokio-rs/loom/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/tokio-rs/loom/languages",
            "stargazers_url": "https://api.github.com/repos/tokio-rs/loom/stargazers",
            "contributors_url": "https://api.github.com/repos/tokio-rs/loom/contributors",
            "subscribers_url": "https://api.github.com/repos/tokio-rs/loom/subscribers",
            "subscription_url": "https://api.github.com/repos/tokio-rs/loom/subscription",
            "commits_url": "https://api.github.com/repos/tokio-rs/loom/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/tokio-rs/loom/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/tokio-rs/loom/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/tokio-rs/loom/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/tokio-rs/loom/contents/{+path}",
            "compare_url": "https://api.github.com/repos/tokio-rs/loom/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/tokio-rs/loom/merges",
            "archive_url": "https://api.github.com/repos/tokio-rs/loom/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/tokio-rs/loom/downloads",
            "issues_url": "https://api.github.com/repos/tokio-rs/loom/issues{/number}",
            "pulls_url": "https://api.github.com/repos/tokio-rs/loom/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/tokio-rs/loom/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/tokio-rs/loom/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/tokio-rs/loom/labels{/name}",
            "releases_url": "https://api.github.com/repos/tokio-rs/loom/releases{/id}",
            "deployments_url": "https://api.github.com/repos/tokio-rs/loom/deployments",
            "created_at": "2018-12-15T06:11:47Z",
            "updated_at": "2022-12-04T02:45:35Z",
            "pushed_at": "2022-11-25T16:49:51Z",
            "git_url": "git://github.com/tokio-rs/loom.git",
            "ssh_url": "git@github.com:tokio-rs/loom.git",
            "clone_url": "https://github.com/tokio-rs/loom.git",
            "svn_url": "https://github.com/tokio-rs/loom",
            "homepage": "",
            "size": 450,
            "stargazers_count": 1422,
            "watchers_count": 1422,
            "language": "Rust",
            "has_issues": true,
            "has_projects": false,
            "has_downloads": true,
            "has_wiki": false,
            "has_pages": false,
            "has_discussions": false,
            "forks_count": 80,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 67,
            "license": {
                "key": "mit",
                "name": "MIT License",
                "spdx_id": "MIT",
                "url": "https://api.github.com/licenses/mit",
                "node_id": "MDc6TGljZW5zZTEz"
            },
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [],
            "visibility": "public",
            "forks": 80,
            "open_issues": 67,
            "watchers": 1422,
            "default_branch": "master",
            "score": 1.0
        },
        {
            "id": 39320212,
            "node_id": "MDEwOlJlcG9zaXRvcnkzOTMyMDIxMg==",
            "name": "rust-skeptic",
            "full_name": "budziq/rust-skeptic",
            "private": false,
            "owner": {
                "login": "budziq",
                "id": 221000,
                "node_id": "MDQ6VXNlcjIyMTAwMA==",
                "avatar_url": "https://avatars.githubusercontent.com/u/221000?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/budziq",
                "html_url": "https://github.com/budziq",
                "followers_url": "https://api.github.com/users/budziq/followers",
                "following_url": "https://api.github.com/users/budziq/following{/other_user}",
                "gists_url": "https://api.github.com/users/budziq/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/budziq/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/budziq/subscriptions",
                "organizations_url": "https://api.github.com/users/budziq/orgs",
                "repos_url": "https://api.github.com/users/budziq/repos",
                "events_url": "https://api.github.com/users/budziq/events{/privacy}",
                "received_events_url": "https://api.github.com/users/budziq/received_events",
                "type": "User",
                "site_admin": false
            },
            "html_url": "https://github.com/budziq/rust-skeptic",
            "description": "Test your Rust Markdown documentation via Cargo",
            "fork": false,
            "url": "https://api.github.com/repos/budziq/rust-skeptic",
            "forks_url": "https://api.github.com/repos/budziq/rust-skeptic/forks",
            "keys_url": "https://api.github.com/repos/budziq/rust-skeptic/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/budziq/rust-skeptic/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/budziq/rust-skeptic/teams",
            "hooks_url": "https://api.github.com/repos/budziq/rust-skeptic/hooks",
            "issue_events_url": "https://api.github.com/repos/budziq/rust-skeptic/issues/events{/number}",
            "events_url": "https://api.github.com/repos/budziq/rust-skeptic/events",
            "assignees_url": "https://api.github.com/repos/budziq/rust-skeptic/assignees{/user}",
            "branches_url": "https://api.github.com/repos/budziq/rust-skeptic/branches{/branch}",
            "tags_url": "https://api.github.com/repos/budziq/rust-skeptic/tags",
            "blobs_url": "https://api.github.com/repos/budziq/rust-skeptic/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/budziq/rust-skeptic/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/budziq/rust-skeptic/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/budziq/rust-skeptic/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/budziq/rust-skeptic/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/budziq/rust-skeptic/languages",
            "stargazers_url": "https://api.github.com/repos/budziq/rust-skeptic/stargazers",
            "contributors_url": "https://api.github.com/repos/budziq/rust-skeptic/contributors",
            "subscribers_url": "https://api.github.com/repos/budziq/rust-skeptic/subscribers",
            "subscription_url": "https://api.github.com/repos/budziq/rust-skeptic/subscription",
            "commits_url": "https://api.github.com/repos/budziq/rust-skeptic/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/budziq/rust-skeptic/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/budziq/rust-skeptic/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/budziq/rust-skeptic/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/budziq/rust-skeptic/contents/{+path}",
            "compare_url": "https://api.github.com/repos/budziq/rust-skeptic/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/budziq/rust-skeptic/merges",
            "archive_url": "https://api.github.com/repos/budziq/rust-skeptic/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/budziq/rust-skeptic/downloads",
            "issues_url": "https://api.github.com/repos/budziq/rust-skeptic/issues{/number}",
            "pulls_url": "https://api.github.com/repos/budziq/rust-skeptic/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/budziq/rust-skeptic/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/budziq/rust-skeptic/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/budziq/rust-skeptic/labels{/name}",
            "releases_url": "https://api.github.com/repos/budziq/rust-skeptic/releases{/id}",
            "deployments_url": "https://api.github.com/repos/budziq/rust-skeptic/deployments",
            "created_at": "2015-07-19T02:51:29Z",
            "updated_at": "2022-11-17T17:19:40Z",
            "pushed_at": "2022-11-04T21:14:40Z",
            "git_url": "git://github.com/budziq/rust-skeptic.git",
            "ssh_url": "git@github.com:budziq/rust-skeptic.git",
            "clone_url": "https://github.com/budziq/rust-skeptic.git",
            "svn_url": "https://github.com/budziq/rust-skeptic",
            "homepage": "",
            "size": 229,
            "stargazers_count": 276,
            "watchers_count": 276,
            "language": "Rust",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "has_discussions": false,
            "forks_count": 42,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 29,
            "license": {
                "key": "apache-2.0",
                "name": "Apache License 2.0",
                "spdx_id": "Apache-2.0",
                "url": "https://api.github.com/licenses/apache-2.0",
                "node_id": "MDc6TGljZW5zZTI="
            },
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [],
            "visibility": "public",
            "forks": 42,
            "open_issues": 29,
            "watchers": 276,
            "default_branch": "master",
            "score": 1.0
        },
        {
            "id": 165561258,
            "node_id": "MDEwOlJlcG9zaXRvcnkxNjU1NjEyNTg=",
            "name": "insta",
            "full_name": "mitsuhiko/insta",
            "private": false,
            "owner": {
                "login": "mitsuhiko",
                "id": 7396,
                "node_id": "MDQ6VXNlcjczOTY=",
                "avatar_url": "https://avatars.githubusercontent.com/u/7396?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/mitsuhiko",
                "html_url": "https://github.com/mitsuhiko",
                "followers_url": "https://api.github.com/users/mitsuhiko/followers",
                "following_url": "https://api.github.com/users/mitsuhiko/following{/other_user}",
                "gists_url": "https://api.github.com/users/mitsuhiko/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/mitsuhiko/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mitsuhiko/subscriptions",
                "organizations_url": "https://api.github.com/users/mitsuhiko/orgs",
                "repos_url": "https://api.github.com/users/mitsuhiko/repos",
                "events_url": "https://api.github.com/users/mitsuhiko/events{/privacy}",
                "received_events_url": "https://api.github.com/users/mitsuhiko/received_events",
                "type": "User",
                "site_admin": false
            },
            "html_url": "https://github.com/mitsuhiko/insta",
            "description": "A snapshot testing library for rust",
            "fork": false,
            "url": "https://api.github.com/repos/mitsuhiko/insta",
            "forks_url": "https://api.github.com/repos/mitsuhiko/insta/forks",
            "keys_url": "https://api.github.com/repos/mitsuhiko/insta/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/mitsuhiko/insta/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/mitsuhiko/insta/teams",
            "hooks_url": "https://api.github.com/repos/mitsuhiko/insta/hooks",
            "issue_events_url": "https://api.github.com/repos/mitsuhiko/insta/issues/events{/number}",
            "events_url": "https://api.github.com/repos/mitsuhiko/insta/events",
            "assignees_url": "https://api.github.com/repos/mitsuhiko/insta/assignees{/user}",
            "branches_url": "https://api.github.com/repos/mitsuhiko/insta/branches{/branch}",
            "tags_url": "https://api.github.com/repos/mitsuhiko/insta/tags",
            "blobs_url": "https://api.github.com/repos/mitsuhiko/insta/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/mitsuhiko/insta/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/mitsuhiko/insta/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/mitsuhiko/insta/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/mitsuhiko/insta/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/mitsuhiko/insta/languages",
            "stargazers_url": "https://api.github.com/repos/mitsuhiko/insta/stargazers",
            "contributors_url": "https://api.github.com/repos/mitsuhiko/insta/contributors",
            "subscribers_url": "https://api.github.com/repos/mitsuhiko/insta/subscribers",
            "subscription_url": "https://api.github.com/repos/mitsuhiko/insta/subscription",
            "commits_url": "https://api.github.com/repos/mitsuhiko/insta/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/mitsuhiko/insta/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/mitsuhiko/insta/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/mitsuhiko/insta/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/mitsuhiko/insta/contents/{+path}",
            "compare_url": "https://api.github.com/repos/mitsuhiko/insta/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/mitsuhiko/insta/merges",
            "archive_url": "https://api.github.com/repos/mitsuhiko/insta/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/mitsuhiko/insta/downloads",
            "issues_url": "https://api.github.com/repos/mitsuhiko/insta/issues{/number}",
            "pulls_url": "https://api.github.com/repos/mitsuhiko/insta/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/mitsuhiko/insta/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/mitsuhiko/insta/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/mitsuhiko/insta/labels{/name}",
            "releases_url": "https://api.github.com/repos/mitsuhiko/insta/releases{/id}",
            "deployments_url": "https://api.github.com/repos/mitsuhiko/insta/deployments",
            "created_at": "2019-01-13T22:25:41Z",
            "updated_at": "2022-12-03T17:54:00Z",
            "pushed_at": "2022-12-03T13:02:57Z",
            "git_url": "git://github.com/mitsuhiko/insta.git",
            "ssh_url": "git@github.com:mitsuhiko/insta.git",
            "clone_url": "https://github.com/mitsuhiko/insta.git",
            "svn_url": "https://github.com/mitsuhiko/insta",
            "homepage": "https://insta.rs",
            "size": 10214,
            "stargazers_count": 1343,
            "watchers_count": 1343,
            "language": "Rust",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": false,
            "has_pages": false,
            "has_discussions": true,
            "forks_count": 60,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 19,
            "license": {
                "key": "apache-2.0",
                "name": "Apache License 2.0",
                "spdx_id": "Apache-2.0",
                "url": "https://api.github.com/licenses/apache-2.0",
                "node_id": "MDc6TGljZW5zZTI="
            },
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [
                "rust",
                "snapshot-tests",
                "vscode-extension"
            ],
            "visibility": "public",
            "forks": 60,
            "open_issues": 19,
            "watchers": 1343,
            "default_branch": "master",
            "score": 1.0
        }
    ]
}
''';

  test(
    'Items class - fromJoson',
    () async {
      var data = json.decode(githubApiSearchRepositoryReturnDataExample);
      Items result = Items.fromJson({'items': data['items']});

      expect(result.items!.first.id, 77338532);
      expect(result.items!.first.nodeId, "MDEwOlJlcG9zaXRvcnk3NzMzODUzMg==");
      expect(result.items!.first.fullName, "cross-rs/cross");
      expect(result.items!.first.private, false);
      expect(result.items!.first.owner.login, "cross-rs");
      expect(result.items!.first.owner.id, 93954236);
      expect(result.items!.first.owner.url,
          "https://api.github.com/users/cross-rs");
      expect(result.items!.first.owner.starredUrl,
          "https://api.github.com/users/cross-rs/starred{/owner}{/repo}");
      expect(result.items!.first.owner.subscriptionsUrl,
          "https://api.github.com/users/cross-rs/subscriptions");
    },
  );

  test(
    'SearchRepositoryModel class - fromJoson',
    () async {
      var data = json.decode(githubApiSearchRepositoryReturnDataExample);
      SearchRepositoryModel result = SearchRepositoryModel.fromJson(data);

      expect(result.items!.first.id, 77338532);
      expect(result.items!.first.nodeId, "MDEwOlJlcG9zaXRvcnk3NzMzODUzMg==");
      expect(result.items!.first.fullName, "cross-rs/cross");
      expect(result.items!.first.private, false);
      expect(result.items!.first.owner.login, "cross-rs");
      expect(result.items!.first.owner.id, 93954236);
      expect(result.items!.first.owner.url,
          "https://api.github.com/users/cross-rs");
      expect(result.items!.first.owner.starredUrl,
          "https://api.github.com/users/cross-rs/starred{/owner}{/repo}");
      expect(result.items!.first.owner.subscriptionsUrl,
          "https://api.github.com/users/cross-rs/subscriptions");

      expect(result.totalCount, 5050);
      expect(result.incompleteResults, false);
    },
  );
}
